/*
================================================================================
Delta Table Schema for UPS Bill
================================================================================
Purpose: Staging table for raw UPS bill CSV data (1:1 column mapping).
         All columns are VARCHAR to handle any incoming data format.
         ADF Copy Activity loads CSV directly into this table.

Format: Narrow (one row per charge) - NO unpivot needed

Note: This table is recreated/truncated by ADF before each load.
================================================================================
*/

CREATE TABLE test.delta_ups_bill (
    [Version] VARCHAR(50) NULL,
    [Recipient Number] VARCHAR(50) NULL,
    [Account Number] VARCHAR(50) NULL,
    [Account Country] VARCHAR(50) NULL,
    [Invoice Date] VARCHAR(50) NULL,
    [Invoice Number] VARCHAR(50) NULL,
    [Invoice Type Code] VARCHAR(50) NULL,
    [Invoice Type Detail Code] VARCHAR(50) NULL,
    [Account Tax ID] VARCHAR(50) NULL,
    [Invoice Currency Code] VARCHAR(50) NULL,
    [Invoice Amount] VARCHAR(50) NULL,
    [Transaction Date] VARCHAR(50) NULL,
    [Pickup Record Number] VARCHAR(50) NULL,
    [Lead Shipment Number] VARCHAR(50) NULL,
    [World Ease Number] VARCHAR(50) NULL,
    [Shipment Reference Number 1] VARCHAR(500) NULL,
    [Shipment Reference Number 2] VARCHAR(500) NULL,
    [Bill Option Code] VARCHAR(50) NULL,
    [Package Quantity] VARCHAR(50) NULL,
    [Oversize Quantity] VARCHAR(50) NULL,
    [Tracking Number] VARCHAR(255) NULL,
    [Package Reference Number 1] VARCHAR(500) NULL,
    [Package Reference Number 2] VARCHAR(500) NULL,
    [Package Reference Number 3] VARCHAR(500) NULL,
    [Package Reference Number 4] VARCHAR(500) NULL,
    [Package Reference Number 5] VARCHAR(500) NULL,
    [Entered Weight] VARCHAR(50) NULL,
    [Entered Weight Unit of Measure] VARCHAR(50) NULL,
    [Billed Weight] VARCHAR(50) NULL,
    [Billed Weight Unit of Measure] VARCHAR(50) NULL,
    [Container Type] VARCHAR(50) NULL,
    [Billed Weight Type] VARCHAR(50) NULL,
    [Package Dimensions] VARCHAR(100) NULL,
    [Zone] VARCHAR(50) NULL,
    [Charge Category Code] VARCHAR(50) NULL,
    [Charge Category Detail Code] VARCHAR(50) NULL,
    [Charge Source] VARCHAR(50) NULL,
    [Type Code 1] VARCHAR(50) NULL,
    [Type Detail Code 1] VARCHAR(50) NULL,
    [Type Detail Value 1] VARCHAR(50) NULL,
    [Type Code 2] VARCHAR(50) NULL,
    [Type Detail Code 2] VARCHAR(50) NULL,
    [Type Detail Value 2] VARCHAR(50) NULL,
    [Charge Classification Code] VARCHAR(50) NULL,
    [Charge Description Code] VARCHAR(50) NULL,
    [Charge Description] VARCHAR(255) NULL,
    [Charged Unit Quantity] VARCHAR(50) NULL,
    [Basis Currency Code] VARCHAR(50) NULL,
    [Basis Value] VARCHAR(50) NULL,
    [Tax Indicator] VARCHAR(50) NULL,
    [Transaction Currency Code] VARCHAR(50) NULL,
    [Incentive Amount] VARCHAR(50) NULL,
    [Net Amount] VARCHAR(50) NULL,
    [Miscellaneous Currency Code] VARCHAR(50) NULL,
    [Miscellaneous Incentive Amount] VARCHAR(50) NULL,
    [Miscellaneous Net Amount] VARCHAR(50) NULL,
    [Alternate Invoicing Currency Code] VARCHAR(50) NULL,
    [Alternate Invoice Amount] VARCHAR(50) NULL,
    [Invoice Exchange Rate] VARCHAR(50) NULL,
    [Tax Variance Amount] VARCHAR(50) NULL,
    [Currency Variance Amount] VARCHAR(50) NULL,
    [Invoice Level Charge] VARCHAR(50) NULL,
    [Invoice Due Date] VARCHAR(50) NULL,
    [Alternate Invoice Number] VARCHAR(50) NULL,
    [Store Number] VARCHAR(50) NULL,
    [Customer Reference Number] VARCHAR(500) NULL,
    [Sender Name] VARCHAR(255) NULL,
    [Sender Company Name] VARCHAR(255) NULL,
    [Sender Address Line 1] VARCHAR(255) NULL,
    [Sender Address Line 2] VARCHAR(255) NULL,
    [Sender City] VARCHAR(100) NULL,
    [Sender State] VARCHAR(50) NULL,
    [Sender Postal] VARCHAR(100) NULL,
    [Sender Country] VARCHAR(50) NULL,
    [Receiver Name] VARCHAR(255) NULL,
    [Receiver Company Name] VARCHAR(255) NULL,
    [Receiver Address Line 1] VARCHAR(255) NULL,
    [Receiver Address Line 2] VARCHAR(255) NULL,
    [Receiver City] VARCHAR(100) NULL,
    [Receiver State] VARCHAR(50) NULL,
    [Receiver Postal] VARCHAR(100) NULL,
    [Receiver Country] VARCHAR(50) NULL,
    [Third Party Name] VARCHAR(255) NULL,
    [Third Party Company Name] VARCHAR(255) NULL,
    [Third Party Address Line 1] VARCHAR(255) NULL,
    [Third Party Address Line 2] VARCHAR(255) NULL,
    [Third Party City] VARCHAR(100) NULL,
    [Third Party State] VARCHAR(50) NULL,
    [Third Party Postal] VARCHAR(100) NULL,
    [Third Party Country] VARCHAR(50) NULL,
    [Sold To Name] VARCHAR(255) NULL,
    [Sold To Company Name] VARCHAR(255) NULL,
    [Sold To Address Line 1] VARCHAR(255) NULL,
    [Sold To Address Line 2] VARCHAR(255) NULL,
    [Sold To City] VARCHAR(100) NULL,
    [Sold To State] VARCHAR(50) NULL,
    [Sold To Postal] VARCHAR(100) NULL,
    [Sold To Country] VARCHAR(50) NULL,
    [Miscellaneous Address Qual 1] VARCHAR(50) NULL,
    [Miscellaneous Address 1 Name] VARCHAR(255) NULL,
    [Miscellaneous Address 1 Company Name] VARCHAR(255) NULL,
    [Miscellaneous Address 1 Address Line 1] VARCHAR(255) NULL,
    [Miscellaneous Address 1 Address Line 2] VARCHAR(255) NULL,
    [Miscellaneous Address 1 City] VARCHAR(100) NULL,
    [Miscellaneous Address 1 State] VARCHAR(50) NULL,
    [Miscellaneous Address 1 Postal] VARCHAR(100) NULL,
    [Miscellaneous Address 1 Country] VARCHAR(50) NULL,
    [Miscellaneous Address Qual 2] VARCHAR(50) NULL,
    [Miscellaneous Address 2 Name] VARCHAR(255) NULL,
    [Miscellaneous Address 2 Company Name] VARCHAR(255) NULL,
    [Miscellaneous Address 2 Address Line 1] VARCHAR(255) NULL,
    [Miscellaneous Address 2 Address Line 2] VARCHAR(255) NULL,
    [Miscellaneous Address 2 City] VARCHAR(100) NULL,
    [Miscellaneous Address 2 State] VARCHAR(50) NULL,
    [Miscellaneous Address 2 Postal] VARCHAR(100) NULL,
    [Miscellaneous Address 2 Country] VARCHAR(50) NULL,
    [Shipment Date] VARCHAR(50) NULL,
    [Shipment Export Date] VARCHAR(50) NULL,
    [Shipment Import Date] VARCHAR(50) NULL,
    [Entry Date] VARCHAR(50) NULL,
    [Direct Shipment Date] VARCHAR(50) NULL,
    [Shipment Delivery Date] VARCHAR(50) NULL,
    [Shipment Release Date] VARCHAR(50) NULL,
    [Cycle Date] VARCHAR(50) NULL,
    [EFT Date] VARCHAR(50) NULL,
    [Validation Date] VARCHAR(50) NULL,
    [Entry Port] VARCHAR(100) NULL,
    [Entry Number] VARCHAR(100) NULL,
    [Export Place] VARCHAR(100) NULL,
    [Shipment Value Amount] VARCHAR(50) NULL,
    [Shipment Description] VARCHAR(500) NULL,
    [Entered Currency Code] VARCHAR(50) NULL,
    [Customs Number] VARCHAR(100) NULL,
    [Exchange Rate] VARCHAR(50) NULL,
    [Master Air Waybill Number] VARCHAR(100) NULL,
    [EPU] VARCHAR(100) NULL,
    [Entry Type] VARCHAR(50) NULL,
    [CPC Code] VARCHAR(50) NULL,
    [Line Item Number] VARCHAR(50) NULL,
    [Goods Description] VARCHAR(500) NULL,
    [Entered Value] VARCHAR(50) NULL,
    [Duty Amount] VARCHAR(50) NULL,
    [Weight] VARCHAR(50) NULL,
    [Unit of Measure] VARCHAR(50) NULL,
    [Item Quantity] VARCHAR(50) NULL,
    [Item Quantity Unit of Measure] VARCHAR(50) NULL,
    [Import Tax ID] VARCHAR(100) NULL,
    [Declaration Number] VARCHAR(100) NULL,
    [Carrier Name] VARCHAR(255) NULL,
    [CCCD Number] VARCHAR(100) NULL,
    [Cycle Number] VARCHAR(100) NULL,
    [Foreign Trade Reference Number] VARCHAR(100) NULL,
    [Job Number] VARCHAR(100) NULL,
    [Transport Mode] VARCHAR(50) NULL,
    [Tax Type] VARCHAR(50) NULL,
    [Tariff Code] VARCHAR(100) NULL,
    [Tariff Rate] VARCHAR(50) NULL,
    [Tariff Treatment Number] VARCHAR(100) NULL,
    [Contact Name] VARCHAR(255) NULL,
    [Class Number] VARCHAR(50) NULL,
    [Document Type] VARCHAR(50) NULL,
    [Office Number] VARCHAR(100) NULL,
    [Document Number] VARCHAR(100) NULL,
    [Duty Value] VARCHAR(50) NULL,
    [Total Value for Duty] VARCHAR(50) NULL,
    [Excise Tax Amount] VARCHAR(50) NULL,
    [Excise Tax Rate] VARCHAR(50) NULL,
    [GST Amount] VARCHAR(50) NULL,
    [GST Rate] VARCHAR(50) NULL,
    [Order In Council] VARCHAR(100) NULL,
    [Origin Country] VARCHAR(50) NULL,
    [SIMA Access] VARCHAR(50) NULL,
    [Tax Value] VARCHAR(50) NULL,
    [Total Customs Amount] VARCHAR(50) NULL,
    [Miscellaneous Line 1] VARCHAR(500) NULL,
    [Miscellaneous Line 2] VARCHAR(500) NULL,
    [Miscellaneous Line 3] VARCHAR(500) NULL,
    [Miscellaneous Line 4] VARCHAR(500) NULL,
    [Miscellaneous Line 5] VARCHAR(500) NULL,
    [Payor Role Code] VARCHAR(50) NULL,
    [Miscellaneous Line 7] VARCHAR(500) NULL,
    [Miscellaneous Line 8] VARCHAR(500) NULL,
    [Miscellaneous Line 9] VARCHAR(500) NULL,
    [Miscellaneous Line 10] VARCHAR(500) NULL,
    [Miscellaneous Line 11] VARCHAR(500) NULL,
    [Duty Rate] VARCHAR(50) NULL,
    [VAT Basis Amount] VARCHAR(50) NULL,
    [VAT Amount] VARCHAR(50) NULL,
    [VAT Rate] VARCHAR(50) NULL,
    [Other Basis Amount] VARCHAR(50) NULL,
    [Other Amount] VARCHAR(50) NULL,
    [Other Rate] VARCHAR(50) NULL,
    [Other Customs Number Indicator] VARCHAR(50) NULL,
    [Other Customs Number] VARCHAR(100) NULL,
    [Customs Office Name] VARCHAR(255) NULL,
    [Package Dimension Unit Of Measure] VARCHAR(50) NULL,
    [Original Shipment Package Quantity] VARCHAR(50) NULL,
    [Place Holder 24] VARCHAR(50) NULL,
    [Place Holder 25] VARCHAR(50) NULL,
    [Place Holder 26] VARCHAR(50) NULL,
    [Place Holder 27] VARCHAR(50) NULL,
    [Place Holder 28] VARCHAR(50) NULL,
    [Place Holder 29] VARCHAR(50) NULL,
    [Place Holder 30] VARCHAR(50) NULL,
    [Place Holder 31] VARCHAR(50) NULL,
    [BOL # 1] VARCHAR(100) NULL,
    [BOL # 2] VARCHAR(100) NULL,
    [BOL # 3] VARCHAR(100) NULL,
    [BOL # 4] VARCHAR(100) NULL,
    [BOL # 5] VARCHAR(100) NULL,
    [PO # 1] VARCHAR(100) NULL,
    [PO # 2] VARCHAR(100) NULL,
    [PO # 3] VARCHAR(100) NULL,
    [PO # 4] VARCHAR(100) NULL,
    [PO # 5] VARCHAR(100) NULL,
    [PO # 6] VARCHAR(100) NULL,
    [PO # 7] VARCHAR(100) NULL,
    [PO # 8] VARCHAR(100) NULL,
    [PO # 9] VARCHAR(100) NULL,
    [PO # 10] VARCHAR(100) NULL,
    [NMFC] VARCHAR(100) NULL,
    [Detail Class] VARCHAR(50) NULL,
    [Freight Sequence Number] VARCHAR(50) NULL,
    [Declared Freight Class] VARCHAR(50) NULL,
    [Place Holder 34] VARCHAR(50) NULL,
    [Place Holder 35] VARCHAR(50) NULL,
    [Place Holder 36] VARCHAR(50) NULL,
    [Place Holder 37] VARCHAR(50) NULL,
    [Place Holder 38] VARCHAR(50) NULL,
    [Place Holder 39] VARCHAR(50) NULL,
    [Place Holder 40] VARCHAR(50) NULL,
    [Place Holder 41] VARCHAR(50) NULL,
    [Place Holder 42] VARCHAR(50) NULL,
    [Place Holder 43] VARCHAR(50) NULL,
    [Place Holder 44] VARCHAR(50) NULL,
    [Place Holder 45] VARCHAR(50) NULL,
    [Place Holder 46] VARCHAR(50) NULL,
    [Place Holder 47] VARCHAR(50) NULL,
    [Place Holder 48] VARCHAR(50) NULL,
    [Place Holder 49] VARCHAR(50) NULL,
    [Place Holder 50] VARCHAR(50) NULL,
    [Place Holder 51] VARCHAR(50) NULL,
    [Place Holder 52] VARCHAR(50) NULL,
    [Place Holder 53] VARCHAR(50) NULL
);

